### ISSUE TITLE
Hey my pull request merged but due to spamming can you add a label hacktoberfest accepted in my pull request.

### ISSUE THREAD

**Issue by siddharthdeo99** [Harshita-Kanal/Data-Structures-and-algorithms#57]
Hey @Harshita-Kanal  2 days earlier you have merged my bubble sort and union of two array codes in cpp. But due to recent spamming on hacktoberfest 2020 some policy were changed so can you label my pull request to hacktoberfest accepted label? Any help would be appreciated.Thank you
#Hacktoberfest2020

**Comment by caro-oviedo** [comment]
Same here! :(  
It's so sad that all these spam is ruining it for the rest of us that really want to contribute :/

**Comment by Harshita-Kanal** [comment]
I have added the tag to the repository, they have made major changes to their rules due to a lot of spamming which was taking place 🙂

**Comment by siddharthdeo99** [comment]
@Harshita-Kanal Thanks closing issue.
