### ISSUE TITLE
There should be proper directories maintained for each type of Program 

### ISSUE THREAD

**Issue by ATRI2107** [Harshita-Kanal/Data-Structures-and-algorithms#77]
@Harshita-Kanal 
Programs in the repository have been added randomly without any directory structure. For example All sorting related problems should go in a folder named Sorting, similarly for others. I will start by adding a Array Folder which will contain some important codes in it. Then People can start following that up.

**Comment by Harshita-Kanal** [comment]
yes, the content needs to be organized well, thanks for this :)

**Comment by Harshita-Kanal** [comment]
I was just figuring out ways to organize this collection, did not expect these many contributions :smile:

**Comment by ATRI2107** [comment]
@Harshita-Kanal sure
